# pylint: disable=invalid-name
# Generated by Django 4.2.17 on 2024-12-15 08:07

import uuid

import django.db.models.deletion
from django.db import migrations, models

import django_utils.django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                (
                    'id',
                    django_utils.django.db.models.fields.AutoUUID4Field(
                        default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                (
                    'slug',
                    models.SlugField(
                        allow_unicode=True, max_length=100, unique=True, verbose_name='slug'
                    ),
                ),
                (
                    'count',
                    models.BigIntegerField(
                        blank=True, db_index=True, default=0, editable=False, verbose_name='count'
                    ),
                ),
                (
                    'last_used',
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name='last used',
                    ),
                ),
            ],
            options={
                'verbose_name': 'hashtag',
                'verbose_name_plural': 'hashtags',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HashtaggedItem',
            fields=[
                (
                    'id',
                    django_utils.django.db.models.fields.AutoUUID4Field(
                        default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'
                    ),
                ),
                ('object_id', models.UUIDField(db_index=True, verbose_name='object ID')),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name='created at'
                    ),
                ),
                (
                    'content_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_tagged_items',
                        to='contenttypes.contenttype',
                        verbose_name='content type',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_items',
                        to='dju_taggit.hashtag',
                    ),
                ),
            ],
            options={
                'verbose_name': 'hashtagged item',
                'verbose_name_plural': 'hashtagged items',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                (
                    'id',
                    django_utils.django.db.models.fields.AutoUUID4Field(
                        default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'
                    ),
                ),
                ('object_id', models.UUIDField(db_index=True, verbose_name='object ID')),
                (
                    'content_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_tagged_items',
                        to='contenttypes.contenttype',
                        verbose_name='content type',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_items',
                        to='dju_taggit.hashtag',
                    ),
                ),
            ],
            options={
                'verbose_name': 'tagged item',
                'verbose_name_plural': 'tagged items',
                'abstract': False,
                'indexes': [
                    models.Index(
                        fields=['content_type', 'object_id'], name='dju_taggit__content_e986ef_idx'
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='taggeditem',
            constraint=models.UniqueConstraint(
                fields=('content_type', 'object_id', 'tag'), name='dju_taggit__content_f2a59_uniq'
            ),
        ),
        migrations.AddIndex(
            model_name='hashtaggeditem',
            index=models.Index(fields=['tag', 'created_at'], name='dju_taggit__tag_id_01830e_idx'),
        ),
        migrations.AddIndex(
            model_name='hashtaggeditem',
            index=models.Index(
                fields=['content_type', 'object_id'], name='dju_taggit__content_a75846_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='hashtaggeditem',
            constraint=models.UniqueConstraint(
                fields=('content_type', 'object_id', 'tag'), name='dju_taggit__content_7088e_uniq'
            ),
        ),
    ]
